[package]
name = "db_manager"
version = "0.1.0"
authors = ["Mark Ellis <m@rkellis.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.5"
clap = { git = "https://github.com/clap-rs/clap", rev = "3294d18" }
